version: 2
jobs:
  test-2-4: &test
    docker:
      - image: tmaier/docker-compose
        environment:
          SERVICE_NAME: ruby-2-4
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run:
          name: setup
          command: |
            set -x
            docker volume create mtsmfm-language-server-sync
            docker create -v mtsmfm-language-server-sync:/app --name mtsmfm-language-server-sync busybox chown -R 1000:1000 /app
            docker cp . mtsmfm-language-server-sync:/app
            docker start mtsmfm-language-server-sync
      - run: docker-compose run $SERVICE_NAME bin/setup
      - run: docker-compose run $SERVICE_NAME bin/m
  test-2-3:
    <<: *test
    docker:
      - image: tmaier/docker-compose
        environment:
          SERVICE_NAME: ruby-2-3
  test-2-2:
    <<: *test
    docker:
      - image: tmaier/docker-compose
        environment:
          SERVICE_NAME: ruby-2-2
workflows:
  version: 2
  test:
    jobs:
      - test-2-4
      - test-2-3
      - test-2-2
