version: '3.2'
services:
  app:
    build: .
    volumes:
      - ./:/app
      - home:/home/ruby
      - $HOME:/$HOME
      - $HOME/.gitconfig:/home/ruby/.gitconfig:ro
      - $HOME/.ssh:/home/ruby/.ssh:ro
  node:
    image: node:7.10-alpine
    user: node
    working_dir: /app
    volumes:
      - ./:/app
      - home:/home/node
volumes:
  home:
