version: "3.0"
services:
  ruby-2-6: &latest
    build: &build
      context: .
      dockerfile: Dockerfile.development
      args:
        RUBY_VERSION: 2.6.0
    environment:
      LANGUAGE_SERVER_RUBY_REMOTE_ROOT: $PWD
    volumes:
      - vendor:/vendor
      - home:/home/ruby
  ruby-2-5:
    <<: *latest
    build:
      <<: *build
      args:
        RUBY_VERSION: 2.5.3
  ruby-2-4:
    <<: *latest
    build:
      <<: *build
      args:
        RUBY_VERSION: 2.4.5
  ruby-2-3:
    <<: *latest
    build:
      <<: *build
      args:
        RUBY_VERSION: 2.3.8
  ruby-2-2:
    <<: *latest
    build:
      <<: *build
      args:
        RUBY_VERSION: 2.2.10
volumes:
  home:
  vendor:
