version: '3.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - app-sync:/app:nocopy
      - home:/home/ruby
      - $HOME:/$HOME
      - $HOME/.gitconfig:/home/ruby/.gitconfig:ro
      - $HOME/.ssh:/home/ruby/.ssh:ro
      - $HOME/.gem:/home/ruby/.gem
  node:
    image: node:7.10-alpine
    user: node
    working_dir: /app
    volumes:
      - app-sync/:/app
      - home:/home/node
volumes:
  app-sync:
    external: true
  home:
