version: '3.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - mtsmfm-language-server-sync:/app:nocopy
      - home:/home/ruby
      - $HOME/.gitconfig:/home/ruby/.gitconfig:ro
      - $HOME/.ssh:/home/ruby/.ssh:ro
      - $HOME/.gem:/home/ruby/.gem
  node:
    build:
      context: .
      dockerfile: Dockerfile-node.development
    volumes:
      - mtsmfm-language-server-sync:/app:nocopy
      - home:/home/node
volumes:
  mtsmfm-language-server-sync:
    external: true
  home:
