# Continuous testing using guard:
# docker-compose run -v $PWD:/tmp/src -w /tmp/src app bash -c 'bundle && guard'
version: '3.0'
services:
  app: &app
    build: &app-build
      context: .
      dockerfile: Dockerfile.development
      args:
        RUBY_VERSION: 2.4.2
    environment:
      LANGUAGE_SERVER_RUBY_REMOTE_ROOT: $PWD
    volumes:
      - vendor:/vendor
      - home:/home/ruby
  ruby-2-4:
    <<: *app
  ruby-2-3:
    <<: *app
    build:
      <<: *app-build
      args:
        RUBY_VERSION: 2.3.4
  ruby-2-2:
    <<: *app
    build:
      <<: *app-build
      args:
        RUBY_VERSION: 2.2.7
volumes:
  home:
  vendor:
