version: '3.0'
services:
  app: &app
    build: &app-build
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - mtsmfm-language-server-sync:/app:nocopy
      - home:/home/ruby
      - $HOME/.gitconfig:/home/ruby/.gitconfig:ro
      - $HOME/.ssh:/home/ruby/.ssh:ro
      - $HOME/.gem:/home/ruby/.gem
  ruby-2-3:
    <<: *app
    build:
      <<: *app-build
      args:
        RUBY_VERSION: 2.3
  ruby-2-2:
    <<: *app
    build:
      <<: *app-build
      args:
        RUBY_VERSION: 2.2
  node:
    build:
      context: .
      dockerfile: Dockerfile-node.development
    volumes:
      - mtsmfm-language-server-sync:/app:nocopy
      - home:/home/node
volumes:
  mtsmfm-language-server-sync:
    external: true
  home:
